chat-format: "<sse:prefix><sse:name>: <rainbow><sse:message></rainbow>"
group-formats:

emojis:
  heart:
    pattern: '<3'
    text: '<red>❤</red>'
  star:
    pattern: ':star:'
    text: '<yellow>✮</yellow>'
  yes:
    pattern: ':yes:'
    text: '<green>✔</green>'
  no:
    pattern: ':no:'
    text: '<red>✖</red>'
  java:
    pattern: ':java:'
    text: '<b>☕</b>'
